services:
  - type: web
    name: cfg-generator
    env: python
    plan: free
    buildCommand: |
      ./build.sh
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cfg-db
          property: connectionString

databases:
  - name: cfg-db
    plan: free
