services:
  - type: web
    name: cfg-generator
    env: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cfg-db
          property: connectionString

databases:
  - name: cfg-db
    plan: free
